### PR TITLE
Storage get count

### PR DESCRIPTION
**Pull request by Magret1730**
In the db_storage and file_storage, I created two new functions i.e get and count function.

Get function is used to retieve an object based on id while count function is used to count the number of objects in storage. 

There is a test file which you can use to test for the file_storage. Usage: ./test_get_count.py 
You can also run this command "HBNB_MYSQL_USER=hbnb_dev HBNB_MYSQL_PWD=hbnb_dev_pwd HBNB_MYSQL_HOST=localhost HBNB_MYSQL_DB=hbnb_dev_db HBNB_TYPE_STORAGE=db ./test_get_count.py" to test for the db_storage.

### CODE REVIEW

**Comment by Magret1730** [comment]
@millimesi please review if you can.

**Comment by Magret1730** [comment]
@malhaouit please review

**Comment by Magret1730** [comment]
@malhaouit please review.

**Review by malhaouit — COMMENTED** [review]
Functions `get `and **count** are added successfully to db_storage and file_storage.

The test file (test_get_count.py) is there for testing get() and count() functions. (Working)

Additonal note: Check the PEP 8. It still doesn't meet all the requierments.

**Review by malhaouit — APPROVED** [review]

**Comment by malhaouit** [comment]
Good

**Pull request merged**
